# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in auto_traffic_control_example.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rubocop", "~> 1.21"
gem "rubocop-rake", "~> 0.6.0"

gem "atc", path: "../../sdk/ruby"
