---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-github
      - R-ignore

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-rust
      - R-ignore

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-node
      - R-ignore

  - package-ecosystem: "npm"
    directory: "/examples/javascript"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-node
      - R-ignore

  - package-ecosystem: "npm"
    directory: "/examples/typescript"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-node
      - R-ignore

  - package-ecosystem: "npm"
    directory: "/sdk/node"
    schedule:
      interval: "daily"
    assignees:
      - jdno
    reviewers:
      - jdno
    labels:
      - C-dependency
      - L-node
      - R-ignore
