---
- name: A-api
  color: f1c40f
  description: "Tag the gRPC API"
- name: A-cli
  color: f1c40f
  description: "Tag the command-line interface"
- name: A-simulation
  color: f1c40f
  description: "Tag the simulation"
- name: A-ui
  color: f1c40f
  description: "Tag the user interface"
- name: C-bug
  color: 9b59b6
  description: "Report a new bug"
- name: C-dependency
  color: 9b59b6
  description: "Update a dependency"
- name: C-documentation
  color: 9b59b6
  description: "Improve the documentation"
- name: C-epic
  color: 9b59b6
  description: "Track a change that involves multiple issues"
- name: C-feature-request
  color: 9b59b6
  description: "Request a new feature"
- name: L-dotnet
  color: 34495e
  description: "Tag the .NET ecosystem"
- name: L-github
  color: 34495e
  description: "Tag the GitHub ecosystem"
- name: L-java
  color: 34495e
  description: "Tag the Java ecosystem"
- name: L-node
  color: 34495e
  description: "Tag the Node ecosystem"
- name: L-python
  color: 34495e
  description: "Tag the Python ecosystem"
- name: L-ruby
  color: 34495e
  description: "Tag the Ruby ecosystem"
- name: L-rust
  color: 34495e
  description: "Tag the Rust ecosystem"
- name: R-added
  color: 95a5a6
  description: "Add a new feature to the release notes"
- name: R-changed
  color: 95a5a6
  description: "Add a change in existing functionality to the release notes"
- name: R-deprecated
  color: 95a5a6
  description: "Add a soon-to-be removed feature to the release notes"
- name: R-fixed
  color: 95a5a6
  description: "Add a fixed bug to the release notes"
- name: R-ignore
  color: 95a5a6
  description: "Do not add this pull request to the release notes"
- name: R-removed
  color: 95a5a6
  description: "Add a now removed feature to the release notes"
- name: R-security
  color: 95a5a6
  description: "Add a vulnerability warning to the release notes"
