[workspace]
# The 2nd-gen resolver is required to compile wgpu.
resolver = "2"

members = [
    "examples/rust",
    "game",
    "sdk/rust",
    "utilities/debug-client",
    "utilities/test-server",
]
