---
name: Markdown

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: "**.md"

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: "--check **/*.md"
