---
name: Protobuf

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.1.0

      - name: Run Buf
        uses: bufbuild/buf-lint-action@v1.0.0
        with:
          input: protobufs
