---
name: Markdown

"on":
  push:
    paths:
      - "**.md"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: "**.md"

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: "--check **/*.md"
