---
name: Shell

"on":
  push:
    paths:
      - "**.sh"
      - "bin/**"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code with Shellcheck
        uses: ludeeus/action-shellcheck@1.1.0

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.5.0
        with:
          sh_checker_shellcheck_disable: true
