---
name: YAML

"on":
  push:
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run yamllint
        uses: actionshub/yamllint@v1.5.0

  style:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: "--check **/*.{yml,yaml}"
